version: '3.9'

services:

    nginx-proxy:
        image: nginxproxy/nginx-proxy:alpine
        container_name: pdf-reverse-proxy-nginx
        restart: unless-stopped
        volumes:
            - ${DOCKER_SOCK_ROOTLESS_PATH:-/var/run/docker.sock}:/tmp/docker.sock:ro
            - ${NGINX_FILES_PATH:-./nginx}/conf.d:/etc/nginx/conf.d
            - ${NGINX_FILES_PATH:-./nginx}/vhost.d:/etc/nginx/vhost.d
            - ${NGINX_FILES_PATH:-./nginx}/html:/usr/share/nginx/html
            - ${NGINX_FILES_PATH:-./nginx}/certs:/etc/nginx/certs:ro
            - ${NGINX_FILES_PATH:-./nginx}/nginx.conf:/etc/nginx/nginx.conf
        ports:
            - "80:80"
        networks:
            - proxy

    amqproxy:
        image: cloudamqp/amqproxy
        container_name: ${CONTAINER_NAME:-unnamed}-rabbitmq-proxy
        environment:
            - AMQP_URL=amqp://rabbitmq:5672
        depends_on:
            rabbitmq:
                condition: service_healthy
        ports:
            - "5673:5673"
        networks:
            - rabbitmq
    
    rabbitmq:
        build:
            context: ./rabbitmq
        container_name: ${CONTAINER_NAME:-unnamed}-rabbitmq
        environment:
            - RABBITMQ_DEFAULT_USER=guest
            - RABBITMQ_DEFAULT_PASS=guest
        healthcheck:
            test: [ "CMD", "curl", "-f", "http://localhost:15672" ]
            interval: 5s
            timeout: 10s
            retries: 5
        ports:
            - "5672:5672"
            - "15672:15672"
        networks:
            - rabbitmq

networks:
    proxy:
        driver: bridge
        name: docker_engine_reverse_proxy
        
    rabbitmq:
        driver: bridge
        name: pdf_frontend_rabbitmq