apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: minio-console-ingress
  namespace: {{ .Release.Namespace }}
  {{- with .Values.console.ingress.labels }}
  labels: {{ toYaml . | nindent 4 }}
  {{- end }}
  annotations:
    kubernetes.io/ingress.class: "nginx"
    cert-manager.io/cluster-issuer: {{ .Chart.Name }}-letsencrypt
spec:
  {{- with .Values.console.ingress.ingressClassName }}
  ingressClassName: {{ . }}
  {{- end }}
  rules:
    - host: {{ .Values.console.ingress.host }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: "console"
                port:
                  number: {{ .Values.console.ingress.number }}

  tls:
    - hosts:
        - {{ .Values.console.ingress.host }}
      secretName: {{ .Chart.Name }}-letsencrypt
