apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
    name: storage-certificate
    namespace: {{ .Release.Namespace }}
spec:
    secretName: storage-tls
    renewBefore: 240h
    duration: 2160h
    commonName: {{ .Values.operator.ingress.host }}
    dnsNames:
        - {{ .Values.operator.ingress.host }}
    issuerRef:
        name: storage-letsencrypt
        kind: ClusterIssuer