apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
    name: storage-letsencrypt
    namespace: {{ .Release.Namespace }}
spec:
    acme:
        server: https://acme-v02.api.letsencrypt.org/directory
        email: {{ .Values.console.email }}
        privateKeySecretRef:
            name: storage-letsencrypt
        solvers:
            - http01:
                  ingress:
                      class: "nginx"