apiVersion: v1
kind: PersistentVolume
metadata:
    name: pdf-s3-pv
    labels:
        type: local
        app: pdf-s3
spec:
    persistentVolumeReclaimPolicy: Retain
    storageClassName: s3-storage
    capacity:
        storage: '5Gi'
    accessModes:
        - ReadWriteOnce
    hostPath:
        path: /var/www/pvc/api-s3