apiVersion: v1
kind: PersistentVolume
metadata:
    name: pdf-logs-pv
    labels:
        type: local
        app: pdf-logs
spec:
    storageClassName: grafana
    capacity:
        storage: '3Gi'
    accessModes:
        - ReadWriteMany
    hostPath:
        path: /var/www/pvc/api-logs