apiVersion: v1
kind: PersistentVolume
metadata:
    name: pdf-logs-pv
    labels:
        type: local
        app: pdf-logs
spec:
    persistentVolumeReclaimPolicy: Retain
    storageClassName: local-storage
    capacity:
        storage: '3Gi'
    accessModes:
        - ReadWriteOnce
    hostPath:
        path: /var/www/pvc/api-logs