apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}-service
  labels:
    app: {{ .Chart.Name }}
    layer: backend
spec:
  type: ClusterIP
  selector:
    app: {{ .Chart.Name }}
  ports:
    - port: {{ .Values.amqpPort }}
      targetPort: {{ .Values.amqpPort }}
      name: amqp
    - port: {{ .Values.managementPort }}
      targetPort: {{ .Values.managementPort }}
      name: management